export const legazpiData = {
  "LEGAZPI CITY": {
    barangay_list: [
      "Em's Barrio",
      "Em's Barrio South",
      "Em's Barrio East",
      "Sagpon",
      "Sagmin",
      "Bañadero",
      "Baño",
      "Bagumbayan",
      "Pinaric",
      "Cabugao",
      "Maoyod",
      "Tula-Tula",
      "Ilawod West",
      "Ilawod",
      "Ilawod East",
      "Kawit-East Washington Drive",
      "Rizal Street, Ilawod",
      "Cabagñan West",
      "Cabagñan",
      "Cabagñan East",
      "Binanuahan West",
      "Binanuahan East",
      "Imperial Court Subdivision",
      "Rizal Street",
      "Lapu-Lapu",
      "Dinagaan",
      "Victory Village South",
      "Victory Village North",
      "Sabang",
      "Pigcale",
      "Centro-Baybay",
      "San Roque",
      "PNR-Peñaranda Street-Iraya",
      "Oro Site-Magallanes Street",
      "Tinago",
      "Kapantawan",
      "Bitano",
      "Gogon",
      "Bonot",
      "Cruzada",
      "Bogtong",
      "Rawis",
      "Tamaoyan",
      "Pawa",
      "Dita",
      "San Joaquin",
      "Arimbay",
      "Bagong Abre",
      "Bigaa",
      "Padang",
      "Buyuan",
      "Matanag",
      "Bonga",
      "Mabinit",
      "Estanza",
      "Taysan",
      "Dap-Dap",
      "Buragwis",
      "Puro",
      "Lamba",
      "Maslog",
      "Homapon",
      "Mariawa",
      "Bagacay",
      "Imalnod",
      "Banquerohan",
      "Bariis",
      "San Francisco",
      "Buenavista",
      "Cagbacong",
    ],
  },
};